# Generated by Django 3.2.9 on 2023-12-13 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incident_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incident',
            old_name='type_id',
            new_name='type',
        ),
    ]
