# Generated by Django 3.2.9 on 2023-12-27 00:37

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_remove_location_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusteredIncidentsView',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('incident_location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('cluster_size', models.IntegerField()),
            ],
            options={
                'db_table': 'clustered_incidents_view',
                'managed': False,
            },
        ),
    ]
