version: "3"

services:
  web:
    build: .
    command: "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8003:8000"
    volumes:
      - .:/app

volumes:
  pgdata:

networks:
  project_translate:
    driver: bridge
